server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: default
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: password

seata:
  enabled: true
  application-id: ${spring.application.name} #微服务应用名称
  tx-service-group: tomato_goods_tx_group    #此处配置自定义的seata事务分组名称
  enable-auto-data-source-proxy: true    #开启数据库代理
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848 #注册中心nacos地址
      cluster: default #默认集群名
  #  config:
  #    type: nacos
  #    nacos:
  #      server-addr: 127.0.0.1:8848 #配置中心nacos地址
  #      group: DEFAULT_GROUP #分组名 对应服务器端配置
  service:
    vgroup-mapping:
      tomato_goods_tx_group: default #事务分组

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml