server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service

  cloud:
    nacos:
      discovery:
        # Nacos作为服务中心的地址
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置Sentinel dashboard地址
        dashboard: localhost:8086
        # 默认8719端口，加入被占用 自动+1寻找未被占用的端口
        port: 8719
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
#            resource:资源名称;
#            IimitApp:来源应用;
#            grade:國值类型,0表示线程数,1表示QPS;
#            count:单机阈值
#            strategy:流控模式,0表示直接,1表示关联,2表示链路
#            controlbehavior:流控效果,0表示快速失败,1表示 Warm Up,2表示排队等待;
#            cluster Mode:是否集群。
#  [{
#     "resource": "byUrl",
#     "limitApp": "default",
#     "grade": 1,
#     "count": 5,
#     "strategy": 0,
#     "controlBehavior": 0,
#     "clusterMode": false
#   }]
# rule-type:flow、degrade、param-flow、system
  #监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
