server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
#        server-addr: 47.107.129.194:80
        server-addr: localhost:8848
#        heart-beat-interval: 100 #心跳间隔。单位为毫秒。
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8086
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider

feign:
  sentinel:
    enabled: true