server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: 47.107.129.194:80
        server-addr: localhost:8848
        heart-beat-interval: 100 #心跳间隔。单位为毫秒。

management:
  endpoints:
    web:
      exposure:
        include: "*"