server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
#        server-addr: 47.107.129.194:80
        server-addr: localhost:8848
        heart-beat-interval: 100 #心跳间隔。单位为毫秒。

#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider